name: flutter_smart_watch
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json_serializable: ^6.4.1
  # build_runner: ^2.2.1

flutter:
  plugin:
    platforms:
      android:
        package: sstonn.example.flutter_smart_watch
        pluginClass: FlutterSmartWatchPlugin
      ios:
        pluginClass: FlutterSmartWatchPlugin