name: flutter_smart_watch
description: The Flutter library provides a wrapper layer to communicate with apps running on WatchOS and WearOS.
version: 0.0.1
homepage: https://github.com/ssttonn/flutter_smart_watch
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_watch_android:
    path: ../flutter_smart_watch_android/
  flutter_smart_watch_ios:
    path: ../flutter_smart_watch_ios/
  flutter_smart_watch_harmony_os:
    path: ../flutter_smart_watch_harmony_os/
  flutter_smart_watch_platform_interface:
    path: ../flutter_smart_watch_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_smart_watch_android
        package: flutter_smart_watch_harmony_os
      ios:
        default_package: flutter_smart_watch_ios