name: flutter_smart_watch
description: The Flutter library provides a wrapper layer to communicate with apps running on WatchOS and WearOS.
version: 0.0.1
homepage: https://github.com/ssttonn/flutter_smart_watch
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # json_annotation: ^4.7.0
  image_picker: ^0.8.6
  flutter_smart_watch_android:
    path: ../flutter_smart_watch_android/
  flutter_smart_watch_ios:
    path: ../flutter_smart_watch_ios/
  flutter_smart_watch_platform_interface:
    path: ../flutter_smart_watch_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.4.1
  build_runner: ^2.2.1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_smart_watch_android
      ios:
        default_package: flutter_smart_watch_ios