name: flutter_smart_watch_ios
description: IOS implementation of the flutter_smart_watch plugin.
version: 0.0.1
homepage: https://github.com/ssttonn/flutter_smart_watch
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_watch_platform_interface: 
    path: ../flutter_smart_watch_platform_interface
  json_serializable: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: ^4.7.0
  build_runner: ^2.3.0
flutter:
  plugin:
    implements: flutter_smart_watch
    platforms:
      ios:
        pluginClass: FlutterSmartWatchIosPlugin
        dartPluginClass: FlutterSmartWatchIos
