name: flutter_wear_os_connectivity
description: A new Flutter plugin project.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_smart_watch_platform_interface:
    path: ../flutter_smart_watch_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sstonn.flutter_wear_os_connectivity
        pluginClass: FlutterWearOsConnectivityPlugin
        dartPluginClass: FlutterWearOsConnectivity

