name: flutter_smart_watch_platform_interface
description: A common platform interface for the flutter_smart_watch plugin.
version: 0.0.1
home_page: 

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

flutter:
